CREATE DATABASE ApuestasF1
GO
USE ApuestasF1
GO

CREATE TABLE Usuarios (
    ID SMALLINT NOT NULL CONSTRAINT PK_Usuarios PRIMARY KEY
    ,Nombre VARCHAR(30) NOT NULL
    ,Saldo SMALLMONEY NOT NULL CONSTRAINT CK_Saldo CHECK (Saldo >= 0)
    ,Email VARCHAR(50) NOT NULL CONSTRAINT CK_Email CHECK (Email LIKE '%_@__%.__%') CONSTRAINT UQ_Email UNIQUE (Email)
    ,Contraseña VARCHAR(30) NOT NULL
)

CREATE TABLE Transacciones (
    ID SMALLINT NOT NULL CONSTRAINT PK_Transacciones PRIMARY KEY
    ,IDUsuario SMALLINT NOT NULL CONSTRAINT FK_Transacciones FOREIGN KEY REFERENCES Usuarios(ID) ON DELETE CASCADE ON UPDATE CASCADE
    ,Fecha DATETIME NOT NULL
    ,Importe SMALLMONEY NOT NULL
    ,Concepto VARCHAR(100) NULL
)

CREATE TABLE Pilotos(
    Número TINYINT NOT NULL CONSTRAINT PK_Pilotos PRIMARY KEY
    ,Nombre VARCHAR(20) NOT NULL
    ,Apellido VARCHAR(20) NOT NULL
    ,Siglas CHAR(3) NOT NULL
    ,Escudería CHAR(3) NOT NULL
)

CREATE TABLE Carreras (
    Código SMALLINT NOT NULL CONSTRAINT PK_Carreras PRIMARY KEY 
	,Circuito VARCHAR(20) NOT NULL
	,[Fecha y Hora Fin] DATETIME NOT NULL
	,[Número vueltas] TINYINT NOT NULL
)

CREATE TABLE PilotoCarreras(
	 [Número Piloto] TINYINT NOT NULL CONSTRAINT FK_CódigoPiloto FOREIGN KEY REFERENCES Pilotos(Número) ON DELETE CASCADE ON UPDATE CASCADE
	,[Código Carrera] SMALLINT NOT NULL CONSTRAINT FK_CódigoCarrera FOREIGN KEY REFERENCES Carreras(Código) ON DELETE CASCADE ON UPDATE CASCADE
	,Posición TINYINT NULL
	,[Vuelta rápida] TIME NULL
	,CONSTRAINT PK_PilotoCarreras PRIMARY KEY ([Número Piloto], [Código Carrera])
)

CREATE TABLE Apuestas (
	[ID Apuesta] SMALLINT NOT NULL CONSTRAINT PK_Apuestas PRIMARY KEY
	,[ID Usuario] SMALLINT NOT NULL CONSTRAINT FK_ApuestasUsuarios FOREIGN KEY REFERENCES Usuarios(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
	,[Código Carrera] SMALLINT NOT NULL CONSTRAINT FK_ApuestasCarreras FOREIGN KEY REFERENCES Carreras(Código) ON DELETE NO ACTION ON UPDATE NO ACTION
	,[Código Piloto1] TINYINT NOT NULL CONSTRAINT FK_ApuestasPilotos1 FOREIGN KEY REFERENCES Pilotos(Número) ON DELETE NO ACTION ON UPDATE NO ACTION
	,[Código Piloto2] TINYINT NULL CONSTRAINT FK_ApuestasPilotos2 FOREIGN KEY REFERENCES Pilotos(Número) ON DELETE NO ACTION ON UPDATE NO ACTION
	,[Código Piloto3] TINYINT NULL CONSTRAINT FK_ApuestasPilotos3 FOREIGN KEY REFERENCES Pilotos(Número) ON DELETE NO ACTION ON UPDATE NO ACTION
	,Tipo TINYINT  NOT NULL CONSTRAINT CK_Tipo CHECK (Tipo BETWEEN 1 AND 3)
	,Momento SMALLDATETIME NOT NULL
	,Importe SMALLMONEY NOT NULL
	,Cuota DECIMAL(4,2) NOT NULL
)


--1. Funcion de asignacion de la cuota
GO

CREATE or ALTER FUNCTION dbo.AsignarCuota (@CodigoCarrera SMALLINT, @CodigoPiloto1 TINYINT, @CodigoPiloto2 TINYINT, @CodigoPiloto3 TINYINT) RETURNS DECIMAL (4,2) 
AS 

--BEGIN 
--DECLARE @CUOTA DECIMAL(4,2)
--SET @CUOTA = RAND()			--Da error ya que no se puede llamar a una funcion no determinada desde una funcion creada, la solucion es crear una vista
--RETURN @CUOTA
--END

BEGIN
DECLARE @CUOTA DECIMAL(4,2)
SET @CUOTA = (SELECT Valor FROM F1_ValorRandom)
RETURN @CUOTA
END

GO

CREATE VIEW F1_ValorRandom
AS
SELECT RAND() AS Valor

GO
-- No permite modificar ni borrar una apuesta una vez creada.
CREATE TRIGGER BloquearApuesta ON Apuestas
INSTEAD OF UPDATE, DELETE
AS
	THROW 51000, 'La apuesta no se puede modificar ni borrar.', 1
	ROLLBACK
GO