CREATE TABLE Usuarios (
    ID SMALLINT NOT NULL CONSTRAINT PK_Usuarios PRIMARY KEY
    ,Nombre VARCHAR(30) NOT NULL
    ,Saldo SMALLMONEY NOT NULL
    ,Email VARCHAR(50) NOT NULL CONSTRAINT CK_Email CHECK (Email LIKE '%_@__%.__%')
    ,Contrasenha VARCHAR(30) NOT NULL
)

CREATE TABLE Transacciones (
    ID SMALLINT NOT NULL CONSTRAINT PK_Transacciones PRIMARY KEY
    ,IDUsuario SMALLINT NOT NULL CONSTRAINT FK_Transacciones FOREIGN KEY REFERENCES Usuarios(ID) ON DELETE CASCADE ON UPDATE CASCADE
    ,Fecha DATETIME NOT NULL
    ,Importe SMALLMONEY NOT NULL
    ,Concepto VARCHAR(100) NULL
)

CREATE TABLE Pilotos(
    Numero TINYINT NOT NULL CONSTRAINT PK_Pilotos PRIMARY KEY
    ,Nombre VARCHAR(20) NOT NULL
    ,Apellido VARCHAR(20) NOT NULL
    ,Siglas CHAR(3) NOT NULL
    ,Escudería CHAR(3) NOT NULL
)

CREATE TABLE Carreras (
    Código SMALLINT NOT NULL CONSTRAINT PK_Carreras PRIMARY KEY
)

CREATE TABLE Apuestas (
	[ID Apuesta] smallint NOT NULL CONSTRAINT PK_Apuestas PRIMARY KEY
	,[ID Usuario] smallint NOT NULL CONSTRAINT FK_ApuestasUsuarios FOREIGN KEY REFERENCES Usuarios(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
	,[Código Carrera] smallint NOT NULL CONSTRAINT FK_ApuestasCarreras FOREIGN KEY REFERENCES Carreras(Código) ON DELETE NO ACTION ON UPDATE NO ACTION
	,Tipo nvarchar(30) NOT NULL
	,Momento smalldatetime NOT NULL
	,Importe smallmoney NOT NULL
	,Cuota decimal(6,2) NOT NULL
)